name: Release
on:
  workflow_run:
    workflows: [regular-push]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  package:
    name: Create Package
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install node dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}